FROM docker.whknow.kits/repository/kits/tomcat-run:0.0.6
ARG VERSION
ARG COMMIT_SHA
ARG KITSLA_HOST
ENV VERSION $VERSION
ENV COMMIT_SHA $COMMIT_SHA
ENV KITSLA_HOST $KITSLA_HOST
ADD inms.war $CATALINA_HOME/webapps/